name = "NumericalMethods"
uuid = "154d3d63-62f4-4409-ad1c-5b6779bffd36"
authors = ["Joby M. Anthony III"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
